- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: go-lang setup
  ansible.legacy.import_role:
    name: common
    tasks_from: go-lang-setup

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
