- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: node setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup

- name: mongo setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup

- name: system service setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
